version: '3.9'

services:
  db:
    container_name: bootcamp_db
    image: postgres:13.4-alpine
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env.dev
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./migrations:/app/migrations
      - ./scripts:/app/scripts

volumes:
  postgres: